# Generated by Django 5.2.4 on 2025-08-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/main/'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_image1',
            field=models.ImageField(blank=True, null=True, upload_to='products/sub/'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/sub/'),
        ),
    ]
